DROP TABLE IF EXISTS tb_admin;

CREATE TABLE `ecell`.`tb_admin` (
  `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `login_id` VARCHAR(30) NOT NULL COMMENT '账号',
  `pwd` VARCHAR(30) NOT NULL COMMENT '口令',
  `name` VARCHAR(30) NOT NULL COMMENT '姓名',
  `status` INTEGER UNSIGNED NOT NULL DEFAULT 0 COMMENT '状态',
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB;
